CREATE DATABASE lab_mysql;

USE DATABASE lab_mysql;
CREATE SCHEMA concesionarios;

CREATE OR REPLACE TABLE Coches (
    ID_Co INT NOT NULL AUTOINCREMENT PRIMARY KEY,
    VIN VARCHAR(50),
    fabricante VARCHAR(50),
    modelo VARCHAR(50),
    ano INT NOT NULL,
    color VARCHAR(50)
);

SELECT * FROM
LAB_MYSQL.CONCESIONARIOS.COCHES;

CREATE OR REPLACE TABLE Clientes (
  ID_Cl INT NOT NULL AUTOINCREMENT PRIMARY KEY,
  id_cliente INT NOT NULL,
  nombre_cliente VARCHAR(50),
  telefono VARCHAR(50),
  email VARCHAR(100),
  direccion VARCHAR(100),
  ciudad VARCHAR(50),
  estado_provincia VARCHAR(50),
  pais VARCHAR(50),
  codigo_postal INT NOT NULL
);

CREATE OR REPLACE TABLE Vendedores (
  ID_V INT NOT NULL AUTOINCREMENT  PRIMARY KEY,
  id_personal INT NOT NULL,
  nombre_personal VARCHAR(50),
  tienda VARCHAR(50)
);

CREATE OR REPLACE TABLE Facturas  (
  ID_F INT NOT NULL AUTOINCREMENT,
  factura INT NOT NULL PRIMARY KEY,
  factura_fecha DATE,
  ID_Co INT NOT NULL,
  ID_Cl INT NOT NULL,
  ID_V INT NOT NULL,
  FOREIGN KEY (ID_Co) REFERENCES Coches(ID_Co),
  FOREIGN KEY (ID_Cl) REFERENCES Clientes(ID_Cl),
  FOREIGN KEY (ID_V) REFERENCES Vendedores(ID_V)
);


